"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useRecipeEditor } from "@/app/components/app-shell";
import { useRecipeVault } from "@/app/components/recipe-vault-provider";
import type { CanonicalRecipe } from "@/lib/recipe-vault";

export function RecipeDetail({ id }: { id: string }) {
  const router = useRouter(); const { openEdit } = useRecipeEditor(); const { remove, storageError } = useRecipeVault(); const [recipe, setRecipe] = useState<CanonicalRecipe | null>(null); const [missing, setMissing] = useState(false); const [confirming, setConfirming] = useState(false);
  useEffect(() => { let live = true; fetch(`/api/recipes/${id}`).then(async (response) => { if (!response.ok) throw new Error(); return response.json() as Promise<{ recipe: CanonicalRecipe }>; }).then((data) => { if (live) setRecipe(data.recipe); }).catch(() => { if (live) setMissing(true); }); return () => { live = false; }; }, [id]);
  if (!recipe) return <section className="page-wrap not-found"><p className="eyebrow">Vault</p><h1>{missing ? "Receptet finns inte" : "Laddar receptet"}</h1><p>{missing ? "Receptet kan ha tagits bort eller länken är felaktig." : "Arkivet läses in."}</p><Link className="button" href="/vault">Tillbaka till Recept</Link></section>;
  return <article className="page-wrap recipe-detail"><nav className="breadcrumbs" aria-label="Brödsmulor"><Link href="/vault">Recept</Link><span>/</span><Link href={`/vault?category=${recipe.categorySlugs[0]}`}>{recipe.categoryNames.join(" · ")}</Link><span>/</span><span aria-current="page">{recipe.title}</span></nav><header className="detail-header"><p className="eyebrow">#{recipe.id} · {recipe.categoryNames.join(" · ")} · {recipe.prepMinutes} min</p><h1>{recipe.title}</h1>{recipe.note && <p>{recipe.note}</p>}<p className="context">{recipe.context}</p><div className="detail-actions"><button className="button" type="button" onClick={() => openEdit(recipe)}>Redigera</button><button className="text-button danger-button" type="button" onClick={() => setConfirming(true)}>Ta bort</button></div></header><div className="detail-grid"><section><h2>Ingredienser</h2><ul className="ingredients">{recipe.ingredients.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ul></section><section><h2>Gör så här</h2><ol className="instructions">{recipe.instructions.map((item, index) => <li key={`${item}-${index}`}>{item}</li>)}</ol></section></div><Link className="back-link" href="/vault">← Tillbaka till Recept</Link>{confirming && <div className="dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setConfirming(false); }}><section className="dialog confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><p className="eyebrow">Bekräfta</p><h2 id="delete-title">Ta bort receptet?</h2><p>Receptet tas bort från det delade arkivet.</p>{storageError && <p className="form-errors" role="alert">{storageError}</p>}<div className="dialog-actions"><button className="text-button" type="button" autoFocus onClick={() => setConfirming(false)}>Avbryt</button><button className="button danger-action" type="button" onClick={async () => { if (await remove(id)) router.push("/vault"); }}>Ta bort</button></div></section></div>}</article>;
}
